/*
 * This file was automatically generated by EvoSuite
 * Mon May 15 13:55:14 GMT 2017
 */

package edu.osu.cs362;

import org.junit.Test;
import static org.junit.Assert.*;
import edu.osu.cs362.Appt;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true) 
public class Appt_ESTest extends Appt_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Appt appt0 = new Appt(31, 31, 31, 90, 31, (String) null, "%h:%m:%s%z");
      appt0.setStartHour(0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Appt appt0 = new Appt(59, 59, 1408, 59, 0, "6n88bx@hM", "6n88bx@hM");
      appt0.setStartHour(0);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Appt appt0 = new Appt(0, 0, 1, 0, 1, "eCW{lX:", "eCW{lX:");
      appt0.setStartMonth(1);
      appt0.getValid();
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Appt appt0 = new Appt(23, 23, 23, 12, 12, (String) null, "WLERBEzng$f349x\"");
      appt0.getTitle();
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Appt appt0 = new Appt(0, 0, 0, 0, 0, "0yNb^hwxHN*qy", "0yNb^hwxHN*qy");
      appt0.getStartYear();
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Appt appt0 = new Appt(11, 11, 11, 11, 11, "fy}NC", "fy}NC");
      appt0.getStartYear();
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Appt appt0 = new Appt(3071, 3071, 3071, 3071, 3071, (String) null, (String) null);
      appt0.getStartMonth();
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Appt appt0 = new Appt((-2403), (-2403), (-907), (-2403), (-2403), "", "<ABQ_");
      appt0.getStartMonth();
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Appt appt0 = new Appt(0, 0, 0, 0, 0, "-/8y[s-d#:1", "-/8y[s-d#:1");
      appt0.getStartMinute();
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Appt appt0 = new Appt((-593), (-4381), 0, (-4381), (-4381), "K.+U`z55,91Pe=~o6", (String) null);
      appt0.getStartMinute();
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Appt appt0 = new Appt(0, 0, (-4901), 3293, 0, "'\u0005a", "'\u0005a");
      appt0.getStartHour();
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Appt appt0 = new Appt(23, 23, 23, 12, 12, (String) null, "WLERBEzng$f349x\"");
      appt0.getStartHour();
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Appt appt0 = new Appt(23, 23, 23, 12, 12, (String) null, "WLERBEzng$f349x\"");
      appt0.setStartDay(0);
      appt0.getStartDay();
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Appt appt0 = new Appt(63, 63, 63, 63, 1, "g#4qARJj*'X~?P$", "g#4qARJj*'X~?P$");
      appt0.getStartDay();
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Appt appt0 = new Appt(3071, (-163), (-163), 3071, (-163), (String) null, (String) null);
      appt0.getDescription();
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Appt appt0 = new Appt(23, 23, 23, 12, 12, (String) null, "WLERBEzng$f349x\"");
      appt0.setDescription("<])H5tQjhS'LEwm,");
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Appt appt0 = new Appt(23, 23, 23, 12, 12, (String) null, "WLERBEzng$f349x\"");
      appt0.setDescription((String) null);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Appt appt0 = new Appt(1, (-11), 1, 1, (-11), "xrZ_]$+!x_EE", ":");
      appt0.setTitle(":");
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Appt appt0 = new Appt(1506, 0, (-870), 355, 1498, "", (String) null);
      appt0.setTitle((String) null);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Appt appt0 = new Appt(23, 23, 23, 12, 12, (String) null, "WLERBEzng$f349x\"");
      appt0.toString();
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Appt appt0 = new Appt(23, 23, 23, 12, 12, (String) null, "WLERBEzng$f349x\"");
      appt0.setStartMonth(185);
      appt0.toString();
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Appt appt0 = new Appt(0, 0, 1, 0, 1, "eCW{lX:", "eCW{lX:");
      appt0.setStartMonth(1);
      appt0.toString();
      assertEquals(1, appt0.getStartMonth());
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Appt appt0 = new Appt(0, 0, 0, 0, 0, "-/8y[s-d#:1", "-/8y[s-d#:1");
      String string0 = appt0.getTitle();
      assertEquals(0, appt0.getStartMinute());
      assertEquals(0, appt0.getStartDay());
      assertEquals("-/8y[s-d#:1", string0);
      assertEquals(0, appt0.getStartHour());
      assertEquals(0, appt0.getStartMonth());
      assertEquals("-/8y[s-d#:1", appt0.getDescription());
      assertEquals(0, appt0.getStartYear());
      assertFalse(appt0.getValid());
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Appt appt0 = new Appt((-1), 201, (-1), (-1374), (-1374), "Z5S:{eg^N%tG", "Z5S:{eg^N%tG");
      int int0 = appt0.getStartYear();
      assertEquals("Z5S:{eg^N%tG", appt0.getDescription());
      assertEquals((-1374), int0);
      assertEquals(201, appt0.getStartMinute());
      assertEquals(-1374, appt0.getStartMonth());
      assertEquals(-1, appt0.getStartDay());
      assertFalse(appt0.getValid());
      assertEquals("Z5S:{eg^N%tG", appt0.getTitle());
      assertEquals(-1, appt0.getStartHour());
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Appt appt0 = new Appt((-3637), (-3637), (-3637), 0, 0, "\t", "e<cKrA+S");
      int int0 = appt0.getStartDay();
      assertEquals("\t", appt0.getTitle());
      assertEquals(-3637, appt0.getStartMinute());
      assertEquals(0, appt0.getStartYear());
      assertEquals(0, appt0.getStartMonth());
      assertEquals("e<cKrA+S", appt0.getDescription());
      assertEquals((-3637), int0);
      assertFalse(appt0.getValid());
      assertEquals(-3637, appt0.getStartHour());
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Appt appt0 = new Appt((-370), 0, (-370), 0, 0, (String) null, (String) null);
      int int0 = appt0.getStartHour();
      assertFalse(appt0.getValid());
      assertEquals((-370), int0);
      assertEquals(-370, appt0.getStartDay());
      assertEquals(0, appt0.getStartYear());
      assertEquals(0, appt0.getStartMinute());
      assertEquals(0, appt0.getStartMonth());
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Appt appt0 = new Appt(23, 23, 23, 12, 12, (String) null, "WLERBEzng$f349x\"");
      appt0.setStartMinute(185);
      assertEquals(185, appt0.getStartMinute());
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Appt appt0 = new Appt(14, 14, 14, 14, 14, "|", "|");
      String string0 = appt0.getDescription();
      assertFalse(appt0.getValid());
      assertEquals("|", appt0.getTitle());
      assertEquals(14, appt0.getStartDay());
      assertEquals("|", string0);
      assertEquals(14, appt0.getStartMonth());
      assertEquals(14, appt0.getStartYear());
      assertEquals(14, appt0.getStartMinute());
      assertEquals(14, appt0.getStartHour());
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      Appt appt0 = new Appt(31, 3162, 1362, 0, 1362, "", "");
      int int0 = appt0.getStartMonth();
      assertEquals(1362, appt0.getStartYear());
      assertEquals(0, int0);
      assertFalse(appt0.getValid());
      assertEquals(3162, appt0.getStartMinute());
      assertEquals(1362, appt0.getStartDay());
      assertEquals(31, appt0.getStartHour());
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      Appt appt0 = new Appt(0, 0, 1, 0, 1, "eCW{lX:", "eCW{lX:");
      assertEquals(1, appt0.getStartYear());
      
      appt0.setStartYear(0);
      assertEquals(0, appt0.getStartYear());
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      Appt appt0 = new Appt(0, 0, 0, 0, 631, "", "Ud`J>.<R");
      boolean boolean0 = appt0.getValid();
      assertEquals(0, appt0.getStartHour());
      assertEquals(0, appt0.getStartMonth());
      assertEquals("Ud`J>.<R", appt0.getDescription());
      assertFalse(boolean0);
      assertEquals("", appt0.getTitle());
      assertEquals(631, appt0.getStartYear());
      assertEquals(0, appt0.getStartMinute());
      assertEquals(0, appt0.getStartDay());
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      Appt appt0 = new Appt(1380, 1380, 1380, 1380, 1380, "", "");
      int int0 = appt0.getStartMinute();
      assertEquals(1380, appt0.getStartMonth());
      assertEquals(1380, int0);
      assertEquals(1380, appt0.getStartDay());
      assertEquals(1380, appt0.getStartHour());
      assertFalse(appt0.getValid());
      assertEquals(1380, appt0.getStartYear());
  }
}
